export const CREATE_ITEM = 'CREATE_ITEM';
export const EDIT_TEXT_ITEM = 'EDIT_TEXT_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const START_EDIT_ITEM = 'START_EDIT_ITEM';
export const FINISH_EDIT_ITEM = 'FINISH_EDIT_ITEM';

