export const CREATE_ITEM = 'CREATE_ITEM';
export const SAVE_TEXT_ITEM = 'SAVE_TEXT_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const START_EDIT_ITEM = 'START_EDIT_ITEM';
export const CANCEL_EDIT_ITEM = 'CANCEL_EDIT_ITEM';

