export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const TOGGLE_EDITING = 'TOGGLE_EDITING';
export const UPDATE_ITEM_TEXT = 'UPDATE_ITEM_TEXT';
export const UPDATE_NEW_ITEM_TEXT = 'UPDATE_NEW_ITEM_TEXT';
export const TEXT_UPDATE_CHANGE = 'TEXT_UPDATE_CHANGE';
