export const ITEM_ADD = 'ITEM_ADD';
export const ITEM_SAVE = 'ITEM_SAVE';
export const ITEM_DELETE = 'ITEM_DELETE';

export const ITEM_VALUE_CHANGED = 'ITEM_VALUE_CHANGED';
export const ITEM_EDITING_START = 'START_EDITING';
export const ITEM_EDITING_STOP = 'STOP_EDITING';

export const ITEM_SAVE_ALL = 'ITEM_SAVE_ALL';
export const ITEM_DELETE_ALL = 'ITEM_DELETE_ALL';
export const ITEM_EDITING_STOP_ALL = 'ITEM_EDITING_STOP_ALL';
