export const ITEM_CREATED = 'ITEM_CREATED';
export const ITEM_OPEN_STATE_CHANGED = 'ITEM_OPEN_STATE_CHANGED';
export const ITEM_CHANGES_SAVED = 'ITEM_CHANGES_SAVED';
export const ITEM_DELETED = 'ITEM_DELETED';
export const UNSAVED_ITEM_DELETED = 'UNSAVED_ITEM_DELETED';
export const ITEM_CLOSED = 'ITEM_CLOSED';

// Syncing
export const ADDED_ITEM_CONFIRMED = 'ADDED_ITEM_CONFIRMED';
export const ITEM_SYNC_REQUESTED = 'ITEM_SYNC_REQUESTED';
export const ITEM_SYNC_SUCCEEDED = 'ITEM_SYNC_SUCCEEDED';
export const ITEM_SYNC_FAILED = 'ITEM_SYNC_FAILED';

// Async actions
export const FETCH_ITEMS_START = 'FETCH_ITEMS_START';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAIL = 'FETCH_ITEMS_FAIL';
