export const ADD_ITEM = 'ADD_ITEM';
export const ITEM_DELETE = 'ITEM_DELETE';
export const ITEM_START_EDITING = 'ITEM_START_EDITING';
export const ITEM_STOP_EDITING = 'ITEM_STOP_EDITING';
export const ITEM_TEXT_UPDATE = 'ITEM_TEXT_UPDATE';
