export const ITEM_CREATED = 'ITEM_CREATED';
export const ITEM_OPENED_FOR_EDITING = 'ITEM_OPENED_FOR_EDITING';
export const ITEM_CHANGES_SAVED = 'ITEM_CHANGES_SAVED';
export const ITEM_CHANGES_CANCELED = 'ITEM_CHANGES_CANCELED';
export const ITEM_DELETED = 'ITEM_DELETED';

// Async actions
export const FETCH_ITEMS = 'FETCH_ITEMS';
