export enum actionTypes {
  ITEM_ADD = 'ITEM_ADD',
  ITEM_SAVE = 'ITEM_SAVE',
  ITEM_DELETE = 'ITEM_DELETE',
  ITEM_VALUE_CHANGED = 'ITEM_VALUE_CHANGED',
  ITEM_EDITING_START = 'START_EDITING',
  ITEM_EDITING_STOP = 'STOP_EDITING',
  ITEM_SAVE_ALL = 'ITEM_SAVE_ALL',
  ITEM_DELETE_ALL = 'ITEM_DELETE_ALL',
  ITEM_EDITING_STOP_ALL = 'ITEM_EDITING_STOP_ALL',
}

