export const ITEM_ADD = 'ITEM_ADD';
export const ITEM_SAVE = 'ITEM_SAVE';
export const ITEM_DELETE = 'ITEM_DELETE';

export const ITEM_VALUE_CHANGED = 'ITEM_VALUE_CHANGED';
export const ITEM_EDITING_START = 'START_EDITING';
export const ITEM_EDITING_STOP = 'STOP_EDITING';

export const NEW_ITEM_CHANGED = 'NEW_ITEM_CHANGED';
export const NEW_ITEM_CHANGE_CANCEL = 'NEW_ITEM_CHANGED_CANCEL';
