const ITEM_CREATED = 'ITEM_CREATED';
const ITEM_TEXT_SELECTED = 'ITEM_TEXT_SELECTED';
const ITEM_CHANGE_SAVED = 'ITEM_CHANGE_SAVED';
const ITEM_CHANGES_CANCELED = 'ITEM_CHANGES_CANCELED';
const ITEM_DELETED = 'ITEM_DELETED';

export {
  ITEM_CREATED,
  ITEM_TEXT_SELECTED,
  ITEM_CHANGE_SAVED,
  ITEM_CHANGES_CANCELED,
  ITEM_DELETED,
};
