const ITEM_CREATED = 'ITEM_CREATED';
const ITEM_OPENED_FOR_EDITING = 'ITEM_OPENED_FOR_EDITING';
const ITEM_CHANGES_SAVED = 'ITEM_CHANGES_SAVED';
const ITEM_CHANGES_CANCELED = 'ITEM_CHANGES_CANCELED';
const ITEM_DELETED = 'ITEM_DELETED';

export {
  ITEM_CREATED,
  ITEM_OPENED_FOR_EDITING,
  ITEM_CHANGES_SAVED,
  ITEM_CHANGES_CANCELED,
  ITEM_DELETED,
};
