const ITEM_CREATED = 'ITEM_CREATED';
const ITEM_CLICKED = 'ITEM_CLICKED';
const ITEM_CHANGE_SAVED = 'ITEM_CHANGE_SAVED';
const ITEM_CHANGE_CANCELED = 'ITEM_CHANGE_CANCELED';
const ITEM_DELETED = 'ITEM_DELETED';

export {
  ITEM_CREATED,
  ITEM_CLICKED,
  ITEM_CHANGE_SAVED,
  ITEM_CHANGE_CANCELED,
  ITEM_DELETED,
};
