export const DELETE_ITEM = 'DELETE_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';
export const TOGGLE_ITEM_VIEW_MODE = 'TOGGLE_ITEM_VIEW_MODE';

export const POSITIVELY_CREATE_ITEM_LOCALLY = 'POSITIVELY_CREATE_ITEM_LOCALLY';
export const ITEM_SAVE_SUCCEED = 'ITEM_SAVE_SUCCEED';
export const ITEM_SAVE_FAILED = 'ITEM_SAVE_FAILED';

export const ITEMS_FETCHING_STARTED = 'ITEMS_FETCHING_STARTED';
export const ITEMS_FETCHING_SUCCEED = 'ITEMS_FETCHING_SUCCEED';
export const ITEMS_FETCHING_FAILED = 'ITEMS_FETCHING_FAILED';

export const DELETE_ERROR = 'DELETE_ERROR';
